language: rust
os: linux
rust:
    - stable
script:
    - rustup component add rust-std --target x86_64-pc-windows-gnu
    - cargo test --all-targets
    - cargo doc --all --all-features --no-deps --target x86_64-pc-windows-gnu
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
    target-branch: gh-pages
    local-dir: target/x86_64-pc-windows-gnu/doc/issue-47048-fix
